module.exports = [
    { continue: { code: '100', desc: 'Continue' } },
    { switchingProtocols: { code: '101', desc: 'Switching Protocols' } },
    { processing: { code: '102', desc: 'Processing' } },
    { ok: { code: '200', desc: 'OK' } },
    { created: { code: '201', desc: 'Created' } },
    { accepted: { code: '202', desc: 'Accepted' } },
    { nonAuthoritativeInformation: { code: '203', desc: 'Non-Authoritative Information' } },
    { noContent: { code: '204', desc: 'No Content' } },
    { resetContent: { code: '205', desc: 'Reset Content' } },
    { partialContent: { code: '206', desc: 'Partial Content' } },
    { multiStatus: { code: '207', desc: 'Multi-Status' } },
    { alreadyReported: { code: '208', desc: 'Already Reported' } },
    { imUsed: { code: '226', desc: 'IM Used' } },
    { multipleChoices: { code: '300', desc: 'Multiple Choices' } },
    { movedPermanently: { code: '301', desc: 'Moved Permanently' } },
    { found: { code: '302', desc: 'Found' } },
    { seeOther: { code: '303', desc: 'See Other' } },
    { notModified: { code: '304', desc: 'Not Modified' } },
    { useProxy: { code: '305', desc: 'Use Proxy' } },
    { temporaryRedirect: { code: '307', desc: 'Temporary Redirect' } },
    { permanentRedirect: { code: '308', desc: 'Permanent Redirect' } },
    { badRequest: { code: '400', desc: 'Bad Request' } },
    { unauthorized: { code: '401', desc: 'Unauthorized' } },
    { paymentRequired: { code: '402', desc: 'Payment Required' } },
    { forbidden: { code: '403', desc: 'Forbidden' } },
    { notFound: { code: '404', desc: 'Not Found' } },
    { methodNotAllowed: { code: '405', desc: 'Method Not Allowed' } },
    { notAcceptable: { code: '406', desc: 'Not Acceptable' } },
    { proxyAuthenticationRequired: { code: '407', desc: 'Proxy Authentication Required' } },
    { requestTimeout: { code: '408', desc: 'Request Timeout' } },
    { conflict: { code: '409', desc: 'Conflict' } },
    { gone: { code: '410', desc: 'Gone' } },
    { lengthRequired: { code: '411', desc: 'Length Required' } },
    { preconditionFailed: { code: '412', desc: 'Precondition Failed' } },
    { payloadTooLarge: { code: '413', desc: 'Payload Too Large' } },
    { uriTooLong: { code: '414', desc: 'URI Too Long' } },
    { unsupportedMediaType: { code: '415', desc: 'Unsupported Media Type' } },
    { rangeNotSatisfiable: { code: '416', desc: 'Range Not Satisfiable' } },
    { expectationFailed: { code: '417', desc: 'Expectation Failed' } },
    { imATeapot: { code: '418', desc: 'I\'m a teapot' } },
    { misdirectedRequest: { code: '421', desc: 'Misdirected Request' } },
    { unprocessableEntity: { code: '422', desc: 'Unprocessable Entity' } },
    { locked: { code: '423', desc: 'Locked' } },
    { failedDependency: { code: '424', desc: 'Failed Dependency' } },
    { unorderedCollection: { code: '425', desc: 'Unordered Collection' } },
    { upgradeRequired: { code: '426', desc: 'Upgrade Required' } },
    { preconditionRequired: { code: '428', desc: 'Precondition Required' } },
    { tooManyRequests: { code: '429', desc: 'Too Many Requests' } },
    { requestHeaderFieldsTooLarge: { code: '431', desc: 'Request Header Fields Too Large' } },
    { unavailableForLegalReasons: { code: '451', desc: 'Unavailable For Legal Reasons' } },
    { internalServerError: { code: '500', desc: 'Internal Server Error' } },
    { notImplemented: { code: '501', desc: 'Not Implemented' } },
    { badGateway: { code: '502', desc: 'Bad Gateway' } },
    { serviceUnavailable: { code: '503', desc: 'Service Unavailable' } },
    { gatewayTimeout: { code: '504', desc: 'Gateway Timeout' } },
    { httpVersionNotSupported: { code: '505', desc: 'HTTP Version Not Supported' } },
    { variantAlsoNegotiates: { code: '506', desc: 'Variant Also Negotiates' } },
    { insufficientStorage: { code: '507', desc: 'Insufficient Storage' } },
    { loopDetected: { code: '508', desc: 'Loop Detected' } },
    { bandwidthLimitExceeded: { code: '509', desc: 'Bandwidth Limit Exceeded' } },
    { notExtended: { code: '510', desc: 'Not Extended' } },
    { networkAuthenticationRequired: { code: '511', desc: 'Network Authentication Required' } }
];
